import { FIELD_LIMITS } from "@/constants/validation";

export const ASSESSMENT_RULES = {
  NAME_MIN: FIELD_LIMITS.TITLE_MIN,
  NAME_MAX: FIELD_LIMITS.TITLE_MAX,
  DESCRIPTION_MAX: FIELD_LIMITS.DESCRIPTION_MAX,
  ROUND_MIN_DURATION: 5,
  ROUND_MAX_DURATION: 480,
  MIN_QUESTIONS_PER_ROUND: 1,
  MAX_ROUNDS: 10,
} as const;
