export type {
  GooglePrefillData,
  CandidateQuestion,
  CandidateQuestionOption,
  CandidateSubmissionDetail,
  SessionState,
  WsMessage,
  MonitoringConfig,
  RoundConfig,
  RoundData,
  Submission,
  SubmissionStatusResponse,
  MalpracticeEvent,
  Screenshot,
  CandidateSchedule,
  VersionSummary,
  RoundResult,
  QuestionAnswer,
} from "./candidate.types";
