import { FIELD_LIMITS } from "@/constants/validation";

export const QUESTION_RULES = {
  TEXT_MIN: 10,
  TEXT_MAX: FIELD_LIMITS.DESCRIPTION_MAX,
  CATEGORY_NAME_MIN: FIELD_LIMITS.NAME_MIN,
  CATEGORY_NAME_MAX: FIELD_LIMITS.NAME_MAX,
  OPTION_TEXT_MAX: FIELD_LIMITS.SHORT_TEXT_MAX,
  MIN_OPTIONS: 2,
  MAX_OPTIONS: 6,
} as const;
